apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backendgo-service
  name: backendgo-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backendgo
  type: LoadBalancer
status:
  loadBalancer: {}
