apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontendflask-service
  name: frontendflask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: frontendflask
  type: LoadBalancer
status:
  loadBalancer: {}
