apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontendflask
  name: frontendflask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendflask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontendflask
    spec:
      containers:
      - image: maeddes/frontendflask:hse24
        name: frontendflask
        resources: {}
        env: # Umgebungsvariablen hinzugefügt
        - name:  API_URL
          value: "http://app:8080/api/shopping" 
status: {}
